CREATE DATABASE test1;
USE test1;
CREATE OR ALTER TABLE tbl_ersteTabelle(
	id INT IDENTITY (1000,1) NOT NULL PRIMARY KEY,
	Vorname VARCHAR(50) NOT NULL,
	Nachname VARCHAR(50) NOT NULL,
	email VARCHAR(110) NOT NULL
);
